spring.data.mongodb.uri=mongodb+srv://vipul_professor_27:ijkEA3Dk08nSFJAi@cluster0.xblga6z.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=ecomDB
spring.data.mongodb.auto-index-creation=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Cloudinary Configuration
cloudinary.cloud_name=df9ke8rha
cloudinary.api_key=262199395525899
cloudinary.api_secret=TWIVu3J-2Mmvw1ob5I8rXDpi1d0

# Cashfree Configuration
cashfree.client-id=${CASHFREE_CLIENT_ID:dummy_client_id}
cashfree.client-secret=${CASHFREE_CLIENT_SECRET:dummy_client_secret}
cashfree.webhook.secret=${CASHFREE_WEBHOOK_SECRET:dummy_webhook_secret}
cashfree.base-url=https://sandbox.cashfree.com/pg








