spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Cashfree Configuration
cashfree.client-id=${CASHFREE_CLIENT_ID}
cashfree.client-secret=${CASHFREE_CLIENT_SECRET}
cashfree.webhook.secret=${CASHFREE_WEBHOOK_SECRET}
cashfree.base-url=https://api.cashfree.com/pg

# Use the PORT environment variable provided by Render
server.port=${PORT:8080}








